DELETE http://localhost:3001/api/persons/4
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Charles",
    "number" : "09-1234556"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Jo"
}
###
GET http://localhost:3001/api/persons
